server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://120.55.66.50:3306/rbac?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: springbird123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379


mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.marlowe.music.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义jwt配置
self:
  jwt:
    secret: j4ctgjPqlLQ47votUkupQYR3j20kgw2e # 加密密钥
    expire: 300000 # token有效时间 1*60*1000(ms) 5分钟 测试token失效
    header: Authorization # 前端请求时, 请求头规定带上这个头部



